apiVersion: v1
kind: Namespace
metadata:
  name: exotic-travel
  labels:
    name: exotic-travel
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: exotic-travel-quota
  namespace: exotic-travel
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: exotic-travel-limits
  namespace: exotic-travel
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
