apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: exotic-travel
type: Opaque
data:
  # Database credentials (base64 encoded)
  DB_PASSWORD: <base64-encoded-db-password>
  
  # Redis credentials
  REDIS_PASSWORD: <base64-encoded-redis-password>
  
  # JWT secrets
  JWT_PRIVATE_KEY: <base64-encoded-jwt-private-key>
  JWT_PUBLIC_KEY: <base64-encoded-jwt-public-key>
  ENCRYPTION_KEY: <base64-encoded-encryption-key>
  
  # Stripe secrets
  STRIPE_SECRET_KEY: <base64-encoded-stripe-secret-key>
  STRIPE_WEBHOOK_SECRET: <base64-encoded-stripe-webhook-secret>
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: <base64-encoded-stripe-publishable-key>
  
  # SMTP credentials
  SMTP_HOST: <base64-encoded-smtp-host>
  SMTP_USER: <base64-encoded-smtp-user>
  SMTP_PASSWORD: <base64-encoded-smtp-password>
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: exotic-travel
type: kubernetes.io/tls
data:
  tls.crt: <base64-encoded-certificate>
  tls.key: <base64-encoded-private-key>
---
# Example script to create secrets
# kubectl create secret generic app-secrets \
#   --from-literal=DB_PASSWORD=your-db-password \
#   --from-literal=REDIS_PASSWORD=your-redis-password \
#   --from-literal=JWT_PRIVATE_KEY="$(cat jwt-private.key | base64 -w 0)" \
#   --from-literal=JWT_PUBLIC_KEY="$(cat jwt-public.key | base64 -w 0)" \
#   --from-literal=ENCRYPTION_KEY="$(openssl rand -hex 32)" \
#   --from-literal=STRIPE_SECRET_KEY=sk_live_... \
#   --from-literal=STRIPE_WEBHOOK_SECRET=whsec_... \
#   --from-literal=NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_live_... \
#   --from-literal=SMTP_HOST=smtp.yourdomain.com \
#   --from-literal=SMTP_USER=noreply@yourdomain.com \
#   --from-literal=SMTP_PASSWORD=your-smtp-password \
#   --namespace=exotic-travel
#
# kubectl create secret tls tls-secret \
#   --cert=fullchain.pem \
#   --key=privkey.pem \
#   --namespace=exotic-travel
